name: Push gem to RubyGems.org

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    environment:
      name: release
      url: https://rubygems.org/gems/minitest-data

    permissions:
      contents: write
      id-token: write

    steps:
      # Set up
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby

      # Release
      - uses: rubygems/release-gem@v1
